
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi
  namespace: my-web

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi

    spec:
      containers:
      - name: fastapi

        image: fastapi-app:latest
        imagePullPolicy: Never

        env:
        - name: DB_HOST
          value: postgres

        envFrom:
        - secretRef:
            name: postgres-secret

        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service

metadata:
  name: fastapi
  namespace: my-web

spec:
  selector:
    app: fastapi

  ports:
  - port: 80
    targetPort: 8000

  type: NodePort
